@startuml
class KonamiCodeDetector {
    + IsKonamiActivated : bool = false
    + KonamiUpdate() : void
}
class DebugMenu {
    + Click() : void
    + {static} DrawDebugMenu() : void
}
class FunEasterEggs {
    + {static} ChangeGameName() : void
}
IClickable <|-- DebugMenu
@enduml
